<?php
$demoUsers = [
    [
        'id' => 1,
        'name' => 'Admin Demo',
        'email' => 'admin@example.com',
        'password' => 'Password123!',
        'role' => 'admin',
        'language' => 'en',
        'currency' => 'USD',
        'status' => 'active',
    ],
    [
        'id' => 2,
        'name' => 'Agent Demo',
        'email' => 'agent@example.com',
        'password' => 'Password123!',
        'role' => 'agent',
        'language' => 'en',
        'currency' => 'USD',
        'status' => 'active',
    ],
    [
        'id' => 3,
        'name' => 'Buyer Demo',
        'email' => 'buyer@example.com',
        'password' => 'Password123!',
        'role' => 'buyer',
        'language' => 'en',
        'currency' => 'USD',
        'status' => 'active',
    ],
];

$demoProperties = [
    [
        'id' => 101,
        'slug' => 'skyline-penthouse-dubai',
        'title' => 'Skyline Penthouse in Downtown Dubai',
        'description' => 'A premium skyline penthouse with terrace, smart home controls, and concierge service.',
        'property_type' => 'Apartment',
        'listing_type' => 'sale',
        'status' => 'live',
        'price' => 2400000,
        'currency' => 'USD',
        'bedrooms' => 4,
        'bathrooms' => 5,
        'area_sqft' => 4850,
        'country' => 'UAE',
        'city' => 'Dubai',
        'neighborhood' => 'Downtown',
        'address' => 'Downtown Dubai, UAE',
        'latitude' => 25.1972,
        'longitude' => 55.2744,
        'featured' => 1,
        'rating' => 4.9,
        'views' => 1260,
        'agent_name' => 'Michael Chen',
        'agent_email' => 'agent@example.com',
        'created_at' => '2026-04-10 12:00:00',
        'images' => [
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1400&q=80',
            'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80',
        ],
        'amenities' => ['Infinity pool', 'Concierge', 'Gym', 'Private parking'],
    ],
    [
        'id' => 102,
        'slug' => 'riverside-family-apartment-london',
        'title' => 'Riverside Family Apartment',
        'description' => 'Bright family apartment near the river with quick access to schools, transport, and retail.',
        'property_type' => 'Apartment',
        'listing_type' => 'rent',
        'status' => 'live',
        'price' => 5800,
        'currency' => 'USD',
        'bedrooms' => 3,
        'bathrooms' => 2,
        'area_sqft' => 1220,
        'country' => 'UK',
        'city' => 'London',
        'neighborhood' => 'Canary Wharf',
        'address' => 'London, UK',
        'latitude' => 51.5072,
        'longitude' => -0.1276,
        'featured' => 1,
        'rating' => 4.8,
        'views' => 880,
        'agent_name' => 'Sarah Williams',
        'agent_email' => 'agent@example.com',
        'created_at' => '2026-04-11 09:00:00',
        'images' => [
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1400&q=80',
            'https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1400&q=80',
        ],
        'amenities' => ['River view', '24/7 security', 'Balcony', 'Lift access'],
    ],
    [
        'id' => 103,
        'slug' => 'marina-residence-singapore',
        'title' => 'Luxury Marina Residence',
        'description' => 'Modern waterfront residence with premium finish, fitted kitchen, and smart lighting.',
        'property_type' => 'Condo',
        'listing_type' => 'sale',
        'status' => 'pending',
        'price' => 3100000,
        'currency' => 'USD',
        'bedrooms' => 4,
        'bathrooms' => 4,
        'area_sqft' => 3200,
        'country' => 'Singapore',
        'city' => 'Singapore',
        'neighborhood' => 'Marina Bay',
        'address' => 'Singapore',
        'latitude' => 1.2834,
        'longitude' => 103.8607,
        'featured' => 0,
        'rating' => 4.7,
        'views' => 690,
        'agent_name' => 'Michael Chen',
        'agent_email' => 'agent@example.com',
        'created_at' => '2026-04-12 15:20:00',
        'images' => [
            'https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1400&q=80',
            'https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?auto=format&fit=crop&w=1400&q=80',
        ],
        'amenities' => ['Smart lighting', 'Sky lounge', 'Pool', 'Gym'],
    ],
    [
        'id' => 104,
        'slug' => 'designer-penthouse-new-york',
        'title' => 'Designer Penthouse Near Central Park',
        'description' => 'A stylish rental with premium finishes and wide city views near the park.',
        'property_type' => 'Penthouse',
        'listing_type' => 'rent',
        'status' => 'live',
        'price' => 16000,
        'currency' => 'USD',
        'bedrooms' => 2,
        'bathrooms' => 3,
        'area_sqft' => 2050,
        'country' => 'USA',
        'city' => 'New York',
        'neighborhood' => 'Manhattan',
        'address' => 'New York, USA',
        'latitude' => 40.7831,
        'longitude' => -73.9712,
        'featured' => 0,
        'rating' => 5.0,
        'views' => 1530,
        'agent_name' => 'Olivia Brown',
        'agent_email' => 'agent@example.com',
        'created_at' => '2026-04-14 10:45:00',
        'images' => [
            'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80',
            'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1400&q=80',
        ],
        'amenities' => ['Doorman', 'Elevator', 'Gym', 'Washer/dryer'],
    ],
    [
        'id' => 105,
        'slug' => 'minimal-loft-canal-view',
        'title' => 'Minimal Loft with Canal View',
        'description' => 'Bright loft with open plan living, quiet water views, and strong rental demand.',
        'property_type' => 'Loft',
        'listing_type' => 'sale',
        'status' => 'sold',
        'price' => 1150000,
        'currency' => 'USD',
        'bedrooms' => 2,
        'bathrooms' => 2,
        'area_sqft' => 1420,
        'country' => 'Netherlands',
        'city' => 'Amsterdam',
        'neighborhood' => 'Canals',
        'address' => 'Amsterdam, Netherlands',
        'latitude' => 52.3676,
        'longitude' => 4.9041,
        'featured' => 0,
        'rating' => 4.6,
        'views' => 760,
        'agent_name' => 'Sarah Williams',
        'agent_email' => 'agent@example.com',
        'created_at' => '2026-04-15 08:10:00',
        'images' => [
            'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1400&q=80',
            'https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=1400&q=80',
        ],
        'amenities' => ['Canal view', 'Open kitchen', 'Natural light', 'Wood floors'],
    ],
    [
        'id' => 106,
        'slug' => 'family-house-sydney',
        'title' => 'Family House with Garden',
        'description' => 'Low-maintenance family home with private garden, study room, and parking.',
        'property_type' => 'House',
        'listing_type' => 'sale',
        'status' => 'live',
        'price' => 920000,
        'currency' => 'USD',
        'bedrooms' => 4,
        'bathrooms' => 3,
        'area_sqft' => 2300,
        'country' => 'Australia',
        'city' => 'Sydney',
        'neighborhood' => 'North Shore',
        'address' => 'Sydney, Australia',
        'latitude' => -33.8688,
        'longitude' => 151.2093,
        'featured' => 0,
        'rating' => 4.5,
        'views' => 540,
        'agent_name' => 'Olivia Brown',
        'agent_email' => 'agent@example.com',
        'created_at' => '2026-04-16 11:30:00',
        'images' => [
            'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1400&q=80',
            'https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&w=1400&q=80',
        ],
        'amenities' => ['Garden', 'Study', 'Garage', 'Pet friendly'],
    ],
];

$demoTrendingLocations = [
    ['name' => 'Dubai', 'count' => '1,240 homes'],
    ['name' => 'London', 'count' => '980 homes'],
    ['name' => 'New York', 'count' => '1,875 homes'],
    ['name' => 'Singapore', 'count' => '640 homes'],
    ['name' => 'Barcelona', 'count' => '510 homes'],
    ['name' => 'Sydney', 'count' => '430 homes'],
];
